[[channels-and-subs]]
== Channel and Subscribers
include::_attributes.adoc[]
//Define vars
:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus

Channels::
  Channels are an event forwarding and persistence layer where each channel is a separate Kubernetes Custom Resource.  A Channel may be backed by Apache Kafka or InMemoryChannel.  This recipe focuses on InMemoryChannel.

Subscriptions::
  Subscriptions are how you register your service to listen to a particular channel.

[#eventing-channel]
== Channel(Sink)

The https://en.wikipedia.org/wiki/Event-driven_architecture#Event_channel[channel or sink] is an interface between the <<eventing-source,event source>> and the <<eventing-subscriber,subscriber>>. The channels are built in to store the incoming events and distribute the event data to the subscribers. When forwarding event to subscribers the channel transforms the event data as per http://cloudevents.io[CloudEvent] specification.

[#eventing-create-event-channel]
=== Create Event Channel
.link:{github-repo}/{eventing-repo}/channel.yaml[channel.yaml]
[source,yaml,linenums]
----
apiVersion: messaging.knative.dev/v1alpha1
kind: Channel
metadata:
  name: eventinghello-ch #<1> 
----

<1> The name of the channel. Knative makes it addressable, i.e. resolveable to a target (a consumer service)

Run the following commands to create the channel:

:doc-sec: eventing-run-source-sub
:url: {github-repo}/{eventing-repo}/channel.yaml
:url-alt-text: channel.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

[#eventing-verify-event-channel]
==== Verification
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-verify-event-channel]
[source,bash,subs="attributes+,+macros"]
----
kubectl -n {tutorial-namespace} get channels.eventing.knative.dev 
----
copyToClipboard::eventing-run-verify-event-channel[]
--
oc::
+
--
endif::[]

[#eventing-run-oc-verify-event-channel]
[source,bash,subs="attributes+,+macros"]
----
oc -n {tutorial-namespace} get channels.eventing.knative.dev 
----
copyToClipboard::eventing-run-oc-verify-event-channel[]
ifndef::workshop[]
--
====
endif::[]

Running  the above command should return the following result:

[source,bash,subs="attributes+,+macros"]
----
NAME             READY URL
eventinghello-ch True  http://eventinghello-ch-kn-channel.chapter-5.svc.cluster.local
----

[#eventing-source]
== Event Source

The event source listens to external events e.g. a kafka topic or for a file on a FTP server. It is responsible to drain the received event(s) along with its data to a configured https://en.wikipedia.org/wiki/Sink_(computing)[sink].

[#eventing-create-event-source]
=== Create Event Source
.link:{github-repo}/{eventing-repo}/event-source.yaml[event-source.yaml]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: my-cjs
spec:
  schedule: "*/2 * * * *"
  data: '{"message": "From CronJob Source"}'
  sink:
   ref:
    apiVersion: messaging.knative.dev/v1alpha1 # <1>
    kind: Channel # <2>
    name: eventinghello-ch
----

<1> The Channel API is in api-group `messaging.eventing.knative.dev`
<2> Kind is `Channel` instead of direct to a specific service; default is InMemoryChannel implementation

Run the following commands to create the event source resources:

:doc-sec: eventing-run-apply-event-src
:url: {github-repo}/{eventing-repo}/event-source.yaml
:url-alt-text: event-source.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

[#eventing-verify-event-source]
==== Verification
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-verify-event-src]
[source,bash,subs="attributes+,+macros"]
----
kubectl -n {tutorial-namespace} get cronjobsources.sources.eventing.knative.dev 
----
copyToClipboard::eventing-run-verify-event-src[]
--
oc::
+
--
endif::[]
[#eventing-run-oc-verify-event-src]
[source,bash,subs="attributes+,+macros"]
----
oc -n {tutorial-namespace} get cronjobsources.sources.eventing.knative.dev 
----
copyToClipboard::eventing-run-oc-verify-event-src[]
ifndef::workshop[]
--
====
endif::[]

Running  the above command should return the following result:

[source,bash,subs="attributes+,+macros"]
----
NAME     READY   AGE
my-cjs   True    8s
----

include::partial$eventing-snippets.adoc[tag=cronjob-source]

[#eventing-subscriber]
== Event Subscriber

The event subscription is responsible of connecting the channel(sink) with the service. Once a service connected to a channel it starts receiving the events (cloud events).

[#eventing-create-subscribers-services]
=== Create Subscriber Services
.link:{github-repo}/{eventing-repo}/channel-subscriber.yaml[channel-subscriber.yaml]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: eventinghelloa
spec:
  template:
    metadata:
      name: eventinghelloa-v1 #<1>
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: quay.io/rhdevelopers/eventinghello:0.0.1
----
<1> The string of `eventinghelloa` will help you identify this particular service.

[source,yaml]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: eventinghellob
spec:
  template:
    metadata:
      name: eventinghellob-v1 <1>
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: quay.io/rhdevelopers/eventinghello:0.0.1
----

<1> The string of `eventinghellob` will help you identify this particular service.

:doc-sec: create-subscriber-svc-1
:url: {github-repo}/{eventing-repo}/eventing-helloa-sink.yaml
:url-alt-text: eventing-helloa-sink.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]


:doc-sec: create-subscriber-svc-2
:url: {github-repo}/{eventing-repo}/eventing-hellob-sink.yaml
:url-alt-text: eventing-hellob-sink.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

[#eventing-create-subscriber]
=== Create Channel Subscribers

Now create the appropriate `Subscription` for `eventinghelloa` to the Channel `eventinghello-ch`:

[source,yaml]
----
apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: eventinghelloa-sub
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: eventinghello-ch
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: eventinghelloa
----

And create the appropriate `Subscription` for `eventinghellob` to the Channel `eventinghello-ch`:

[source,yaml]
----
apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: eventinghellob-sub
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: eventinghello-ch
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: eventinghellob
----

:doc-sec: create-subscriber-1
:url: {github-repo}/{eventing-repo}/eventing-helloa-sub.yaml
:url-alt-text: eventing-helloa-sub.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]


:doc-sec: create-subscriber-2
:url: {github-repo}/{eventing-repo}/eventing-hellob-sub.yaml
:url-alt-text: eventing-hellob-sub.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

[#eventing-verify-subscriber]
==== Verification

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-verify-subscriber]
[source,bash,subs="attributes+,+macros"]
----
kubectl -n {tutorial-namespace} get subscriptions.eventing.knative.dev 
----
copyToClipboard::eventing-run-verify-subscriber[]
--
oc::
+
--
endif::[]
[#eventing-run-oc-verify-subscriber]
[source,bash,subs="attributes+,+macros"]
----
oc -n {tutorial-namespace} get subscriptions.eventing.knative.dev 
----
copyToClipboard::eventing-run-oc-verify-subscriber[]
ifndef::workshop[]
--
====
endif::[]

Running  the above command should return the following result:

//TODO - update
[source,bash,subs="attributes+,+macros"]
----
NAME                       AGE
event-greeter-subscriber  39s
----

If you wait approximately 2 minutes for the CronJobSource then you will see both `eventinghelloa` and `eventinghellob` begin to run in the {tutorial-namespace}.

.Watch pods in the {tutorial-namespace}
[source,bash,subs="+quotes,attributes+,+macros"]
----
NAME                                                      READY STATUS  AGE
cronjobsource-my-cjs-93544f14-2bf9-11ea-83c7-08002737670c 1/1   Running 2m15s
eventinghelloa-1-deployment-d86bf4847-hvbk6               2/2   Running 5s
eventinghellob-1-deployment-5c986c7586-4clpb              2/2   Running 5s
----

[#eventing-see-what-you-have-deployed]
=== See what you have deployed

==== channel
include::partial$knative-objects.adoc[tag=knative-event-channel]

==== sources
include::partial$knative-objects.adoc[tag=knative-event-cronjob-sources]

==== subscription
include::partial$knative-objects.adoc[tag=knative-event-subscribers]

TIP: Add `-oyaml` to the above commands to get more details about each object that were queried for. 

[#eventing-cleanup]
== Cleanup
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-cleanup2]
[source,bash,subs="attributes+,+macros",linenums]
----
kubectl -n {tutorial-namespace} delete -f eventing-helloa-sink.yaml
kubectl -n {tutorial-namespace} delete -f eventing-helloa-sub.yaml
kubectl -n {tutorial-namespace} delete -f eventing-hellob-sink.yaml
kubectl -n {tutorial-namespace} delete -f eventing-hellob-sub.yaml
kubectl -n {tutorial-namespace} delete -f eventinghello-source-ch.yaml
----
copyToClipboard::eventing-run-cleanup2[]

--
oc::
+
--
endif::[]
[#eventing-run-oc-cleanup2]
[source,bash,subs="attributes+,+macros",linenums]
----
oc -n {tutorial-namespace} delete -f eventing-helloa-sink.yaml
oc -n {tutorial-namespace} delete -f eventing-helloa-sub.yaml
oc -n {tutorial-namespace} delete -f eventing-hellob-sink.yaml
oc -n {tutorial-namespace} delete -f eventing-hellob-sub.yaml
oc -n {tutorial-namespace} delete -f eventinghello-source-ch.yaml
----
copyToClipboard::eventing-run-oc-cleanup2[]
ifndef::workshop[]
--
====

endif::[]
