[[brokers-and-triggers]]
== Triggers and Brokers
include::_attributes.adoc[]

:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus

Use the Knative Eventing `Broker` and `Trigger` Custom Resources to allow for CloudEvent attribute filtering.

[#broker]
== Broker

By labeling *{tutorial-namespace}* namespace with `knative-eventing-injection=enabled` as shown below, will make Knative Eventing to deploy a default Knative Eventing Broker and its related Ingress :

[#label-namespace-for-default-broker]
[source,bash,subs="+quotes,attributes+,+macros"]
----
kubectl label namespace {tutorial-namespace} knative-eventing-injection=enabled
----
copyToClipboard::label-namespace-for-default-broker[]

Verify that the default broker is running:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#watch-ns-for-broker]
[source,bash,subs="+quotes,attributes+,+macros"]
----
watch kubectl --namespace {tutorial-namespace} get broker
----
copyToClipboard::watch-ns-for-broker[]

Running command above should show an output like:

[source,bash]
-----
NAME     READY REASON URL                                                 AGE
default  True         http://default-broker.{tutorial-namespace}.svc.cluster.local   22s
-----

This will also start two additional pods namely `default-broker-filter` and `default-broker-ingress` :

[#watch-ns-for-broker-pods]
[source,bash,subs="+quotes,attributes+,+macros"]
-----
watch kubectl get pods
-----
copyToClipboard::watch-ns-for-broker-pods[]

Running command above should show the following pods in {tutorial-namespace}:

[source,bash]
-----
NAME                                         READY STATUS      AGE
default-broker-filter-c6654bccf-qb272        1/1   Running     18s
default-broker-ingress-7479966dc7-99xvm      1/1   Running     18s
-----
--
oc::
+
--
endif::[]
[#oc-watch-ns-for-broker]
[source,bash,subs="+quotes,attributes+,+macros"]
----
watch oc --namespace {tutorial-namespace} get broker
----
copyToClipboard::oc-watch-ns-for-broker[]

Running command above should show an output like:

[source,bash]
-----
NAME     READY REASON URL                                                 AGE
default  True         http://default-broker.{tutorial-namespace}.svc.cluster.local   22s
-----

This will also start two additional pods namely `default-broker-filter` and `default-broker-ingress` :

[#oc-watch-ns-for-broker-pods]
[source,bash,subs="+quotes,attributes+,+macros"]
-----
watch oc get pods
-----
copyToClipboard::oc-watch-ns-for-broker-pods[]

Running command above should show the following pods in {tutorial-namespace}:

[source,bash]
-----
NAME                                         READY STATUS      AGE
default-broker-filter-c6654bccf-qb272        1/1   Running     18s
default-broker-ingress-7479966dc7-99xvm      1/1   Running     18s
-----
[#eventing-trigger-broker-oc-label-namespace]
[source,bash,subs="attributes+,+macros",linenums]
----
oc label namespace {tutorial-namespace} knative-eventing-injection=enabled
----
copyToClipboard::eventing-trigger-broker-oc-label-namespace[]
ifndef::workshop[]
--
====
endif::[]

[#eventing-service]
== Service 

Now, that you have the broker configured, you need to create the sinks `eventingaloha` and `eventingbonjour`, which will receive the filtered events.

.link:{github-repo}/{eventing-repo}/eventing-aloha-sink.yaml[eventing-aloha-sink.yaml]
[source,yaml,subs="attributes+,+macros"]
----
include::ROOT:example$eventing/eventing-aloha-sink.yaml[]
----

.link:{github-repo}/{eventing-repo}/eventing-bonjour-sink.yaml[eventing-bonjour-sink.yaml]
[source,yaml,subs="attributes+,+macros"]
----
include::ROOT:example$eventing/eventing-bonjour-sink.yaml[]
----

[NOTE]
====
The image being used by both of these services is identical.  However, the difference in name `aloha` vs `bonjour` will make obvious which one is receiving a particular event.
====

[#eventing-deploy-service]
=== Deploy Service

Run the following commands to deploy the `eventingaloha` and `eventingbonjour` services:

:doc-sec: deploy-service-eventing-aloha
:url: {github-repo}/{eventing-repo}/eventing-aloha-sink.yaml
:url-alt-text: eventing-aloha-sink.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

:doc-sec: deploy-service-eventing-bonjour
:url: {github-repo}/{eventing-repo}/eventing-bonjour-sink.yaml
:url-alt-text: eventing-bonjour-sink.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

Wait approximately 60 seconds for `eventingaloha` and `eventingbonjour` to terminate, scale-down to zero before proceeding.

[#eventing-trigger]
== Trigger

Now create the the trigger for `eventingaloha` that will associate the filtered events to a service:

.link:{github-repo}/{eventing-repo}/trigger-helloaloha.yaml[trigger-helloaloha.yaml]
[source,yaml]
----
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: helloaloha
spec:
  filter:
    attributes:
      type: greeting # <1>
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1alpha1
     kind: Service
     name: eventingaloha
----

<1> The `type` is the CloudEvent type that is mapped to the `ce-type` HTTP header.  A Trigger can filter by CloudEvent attributes such as type, source or extension.

Run the following commands to create the trigger:

:doc-sec: eventing-trigger-helloaloha
:url: {github-repo}/{eventing-repo}/trigger-helloaloha.yaml
:url-alt-text: trigger-helloaloha.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

Now create the the trigger for `eventingbonjour` that will associate the filtered events to a service:

.link:{github-repo}/{eventing-repo}/trigger-hellobonjour.yaml[trigger-hellobonjour.yaml]
[source,yaml,linenums,subs="attributes+,+macros"]
----
include::ROOT:example$eventing/trigger-hellobonjour.yaml[]
----

Run the following commands to create the trigger:

:doc-sec: eventing-trigger-hellobonjour
:url: {github-repo}/{eventing-repo}/trigger-hellobonjour.yaml
:url-alt-text: trigger-hellobonjour.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

Verify that your triggers are ready:

include::partial$knative-objects.adoc[tag=knative-triggers]

The command should show the following output:

[source,bash,subs="+quotes,attributes+,+macros"]
----
NAME         READY BROKER  SUBSCRIBER_URI                                      AGE
helloaloha   True  default http://eventingaloha.{tutorial-namespace}.svc.cluster.local   24s
hellobonjour True  default http://eventingbonjour.{tutorial-namespace}.svc.cluster.local 48s
----

[#eventing-see-what-you-have-deployed]
=== See what you have deployed

==== sources
include::partial$knative-objects.adoc[tag=knative-container-event-sources]

==== services
include::partial$knative-objects.adoc[tag=knative-event-services]

[#eventing-trigger-verification]
== Verification

ifndef::workshop[]
[tabs]
====
kubectl::
+
--

Pull out the subscriberURI for `eventhingaloha`:

[#eventing-triggers-verify-sub1]
[source,bash,subs="+quotes,attributes+,+macros"]
----
kubectl get trigger helloaloha -o jsonpath='{.status.subscriberURI}'
----
copyToClipboard::eventing-triggers-verify-sub1[]

The command should show the output as: 
http://eventingaloha.{tutorial-namespace}.svc.cluster.local

Pull out the subscriberURI for `eventhingbonjour`:

[#eventing-triggers-verify-sub2]
[source,bash,subs="+quotes,attributes+,+macros"]
----
kubectl get trigger hellobonjour -o jsonpath='{.status.subscriberURI}'
----
copyToClipboard::eventing-triggers-verify-sub2[]

The command should show the output as: 

http://eventingbonjour.{tutorial-namespace}.svc.cluster.local

As well as broker's subscriberURI:

[#eventing-triggers-verify-sub3]
[source,bash,subs="+quotes,attributes+,+macros"]
----
kubectl get broker default -o jsonpath='{.status.address.url}'
----
copyToClipboard::eventing-triggers-verify-sub3[]

The command should show the output as: 
http://default-broker.{tutorial-namespace}.svc.cluster.local

--
oc::
+
--
endif::[]

Pull out the subscriberURI for `eventhingaloha`:

[#oc-eventing-triggers-verify-sub1]
[source,bash,subs="+quotes,attributes+,+macros"]
----
oc get trigger helloaloha -o jsonpath='{.status.subscriberURI}'
----
copyToClipboard::oc-eventing-triggers-verify-sub1[]

The command should show the output as: 
http://eventingaloha.{tutorial-namespace}.svc.cluster.local

Pull out the subscriberURI for `eventhingbonjour`:

[#oc-eventing-triggers-verify-sub2]
[source,bash,subs="+quotes,attributes+,+macros"]
----
oc get trigger hellobonjour -o jsonpath='{.status.subscriberURI}'
----
copyToClipboard::oc-eventing-triggers-verify-sub2[]

The command should show the output as: 

http://eventingbonjour.{tutorial-namespace}.svc.cluster.local

As well as broker's subscriberURI:

[#oc-eventing-triggers-verify-sub3]
[source,bash,subs="+quotes,attributes+,+macros"]
----
oc get broker default -o jsonpath='{.status.address.url}'
----
copyToClipboard::oc-eventing-triggers-verify-sub3[]

The command should show the output as: 
http://default-broker.{tutorial-namespace}.svc.cluster.local

ifndef::workshop[]
--
====
endif::[]

You should notice that the subscriberURIs are Kubernetes services with the suffix of `{tutorial-namespace}.svc.cluster.local`.  This means they can be interacted with from another pod within the Kubernetes cluster.

Now that you have setup the Broker and Triggers you need to send in some test messages to see the behavior.

First start streaming the logs for the event consumers:

[source,bash,subs="+quotes,attributes+,+macros"]
----
$ *stern eventing -c user-container*
----

Then create a pod for using the `curl` command:

[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curler
  name: curler
spec:
  containers:
  - name: curler
    image: fedora:29 # <1>
    tty: true
----

<1> You can use any image that includes a curl command.

Then exec into the `curler` pod:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--

Create the `curler` pod:

[#trigger-verify-curler]
[source,bash,subs="+quotes,attributes+,+macros"]
-----
kubectl -n {tutorial-namespace} apply -f curler.yaml
-----
copyToClipboard::trigger-verify-curler[]

Exec into the `curler` pod:

[trigger-verify-exec-curler]
[source,bash,subs="+quotes,attributes+,+macros"]
----
kubectl -n {tutorial-namespace} exec -it curler -- /bin/bash
----
copyToClipboard::trigger-verify-exec-curler[]

--
endif::[]
oc::
+
--

Create the `curler` pod:

[#oc-trigger-verify-curler]
[source,bash,subs="+quotes,attributes+,+macros"]
-----
oc -n {tutorial-namespace} apply -f curler.yaml
-----
copyToClipboard::oc-trigger-verify-curler[]

Exec into the `curler` pod:

[oc-trigger-verify-exec-curler]
[source,bash,subs="+quotes,attributes+,+macros"]
----
oc -n {tutorial-namespace} exec -it curler -- /bin/bash
----
copyToClipboard::oc-trigger-verify-exec-curler[]

ifndef::workshop[]
--
====
endif::[]

Using the `curler` pod's shell, curl the subcriberURI for eventingaloha:

[source,bash,subs="+quotes,attributes+,+macros"]
----
$ *curl -v "http://eventingaloha.{tutorial-namespace}.svc.cluster.local" \
-X POST \
-H "Ce-Id: say-hello" \
-H "Ce-Specversion: 1.0" \
-H "Ce-Type: aloha" \
-H "Ce-Source: mycurl" \
-H "Content-Type: application/json" \
-d '{"key":"from a curl"}'*
----

You will then see `eventingaloha` will scale-up to respond to that event:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#trigger-watch-aloha-scale]
[source,bash,subs="+quotes,attributes+,+macros"]
-----
watch kubectl get pods
-----
copyToClipboard::trigger-watch-aloha-scale[]

The command above should show the following output:

[source,bash]
-----
NAME                                        READY STATUS  AGE
curler                                      1/1   Running 59s
default-broker-filter-c6654bccf-vxm5m       1/1   Running 11m
default-broker-ingress-7479966dc7-pvtx6     1/1   Running 11m
eventingaloha-1-deployment-6cdc888d9d-9xnnn 2/2   Running 30s
-----
--
oc::
+
--
[#oc-trigger-watch-aloha-scale]
[source,bash,subs="+quotes,attributes+,+macros"]
-----
watch oc get pods
-----
copyToClipboard::oc-trigger-watch-aloha-scale[]

The command above should show the following output:

[source,bash]
-----
NAME                                        READY STATUS  AGE
curler                                      1/1   Running 59s
default-broker-filter-c6654bccf-vxm5m       1/1   Running 11m
default-broker-ingress-7479966dc7-pvtx6     1/1   Running 11m
eventingaloha-1-deployment-6cdc888d9d-9xnnn 2/2   Running 30s
-----
endif::[]
ifndef::workshop[]
--
====
endif::[]


Next, curl the subcriberURI for `eventingbonjour`:

[source,bash,subs="+quotes,attributes+,+macros"]
----
$ *curl -v "http://eventingbonjour.{tutorial-namespace}.svc.cluster.local" \
-X POST \
-H "Ce-Id: say-hello" \
-H "Ce-Specversion: 1.0" \
-H "Ce-Type: bonjour" \
-H "Ce-Source: mycurl" \
-H "Content-Type: application/json" \
-d '{"key":"from a curl"}'*
----

And you will see the `eventingbonjour` pod scale up:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#trigger-watch-eventingbonjour-scale]
[source,bash,subs="+quotes,attributes+,+macros"]
-----
watch kubectl get pods
-----
copyToClipboard::trigger-watch-eventingbonjour-scale[]

The command above should show the following output:

[source,bash]
-----
NAME                                         READY STATUS  AGE
curler                                       1/1   Running 82s
default-broker-filter-c6654bccf-vxm5m        1/1   Running 11m
default-broker-ingress-7479966dc7-pvtx6      1/1   Running 11m
eventingaloha-1-deployment-6cdc888d9d-9xnnn  2/2   Running 53s
eventingbonjour-1-deployment-fc7858b5b-s9prj 2/2   Running 5s
-----
--
oc::
+
--
[#oc-trigger-watch-eventingbonjour-scale]
[source,bash,subs="+quotes,attributes+,+macros"]
-----
watch oc get pods
-----
copyToClipboard::oc-trigger-watch-eventingbonjour-scale[]

The command above should show the following output:

[source,bash]
-----
NAME                                         READY STATUS  AGE
curler                                       1/1   Running 82s
default-broker-filter-c6654bccf-vxm5m        1/1   Running 11m
default-broker-ingress-7479966dc7-pvtx6      1/1   Running 11m
eventingaloha-1-deployment-6cdc888d9d-9xnnn  2/2   Running 53s
eventingbonjour-1-deployment-fc7858b5b-s9prj 2/2   Running 5s
-----
endif::[]
ifndef::workshop[]
--
====
endif::[]

Now, trigger both `eventingaloha` and `eventingbonjour` by curling the subcriberURI for the broker:

[#trigger-verify-trigger-all]
[source,bash,subs="+quotes,attributes+,+macros"]
----
curl -v "http://default-broker.{tutorial-namespace}.svc.cluster.local" \
-X POST \
-H "Ce-Id: say-hello" \
-H "Ce-Specversion: 1.0" \
-H "Ce-Type: greeting" \
-H "Ce-Source: mycurl" \
-H "Content-Type: application/json" \
-d '{"key":"from a curl"}'
----
copyToClipboard::trigger-verify-trigger-all[]

[NOTE]
====
"Ce-Type: greeting" is the key to insuring that both aloha and bonjour respond to this event
====

And by watching the *{tutorial-namespace}* namespace, you will see both `eventingaloha` and `eventingbonjour` will come to life:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#trigger-watch-all-scale]
[source,bash,subs="+quotes,attributes+,+macros"]
-----
watch kubectl get pods
-----
copyToClipboard::trigger-watch-eventingbonjour-scale[]

The command above should show the following output:

[source,bash]
-----
NAME                                         READY STATUS  AGE
curler                                       1/1   Running 3m21s
default-broker-filter-c6654bccf-vxm5m        1/1   Running 13m
default-broker-ingress-7479966dc7-pvtx6      1/1   Running 13m
eventingaloha-1-deployment-6cdc888d9d-nlpm8  2/2   Running 6s
eventingbonjour-1-deployment-fc7858b5b-btdcr 2/2   Running 6s
-----
--
oc::
+
--
[#oc-trigger-watch-all-scale]
[source,bash,subs="+quotes,attributes+,+macros"]
-----
watch oc get pods
-----
copyToClipboard::oc-trigger-watch-eventingbonjour-scale[]

The command above should show the following output:

[source,bash]
-----
NAME                                         READY STATUS  AGE
curler                                       1/1   Running 3m21s
default-broker-filter-c6654bccf-vxm5m        1/1   Running 13m
default-broker-ingress-7479966dc7-pvtx6      1/1   Running 13m
eventingaloha-1-deployment-6cdc888d9d-nlpm8  2/2   Running 6s
eventingbonjour-1-deployment-fc7858b5b-btdcr 2/2   Running 6s
-----
endif::[]
ifndef::workshop[]
--
====
endif::[]

You can experiment by using different type filters in the Subscription to see how the different subscribed services respond. `Filters` may use an CloudEvent attribute for its criteria.

[#eventing-cleanup]
== Cleanup
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-trigger-broker-cleanup]
[source,bash,subs="attributes+,+macros",linenums]
----
kubectl -n {tutorial-namespace} delete -f eventing-aloha-sink.yaml
kubectl -n {tutorial-namespace} delete -f eventing-bonjour-sink.yaml
kubectl -n {tutorial-namespace} delete -f trigger-helloaloha.yaml
kubectl -n {tutorial-namespace} delete -f trigger-hellobonjour.yaml
kubectl -n {tutorial-namespace} delete -f curler.yaml
----
copyToClipboard::eventing-run-trigger-broker-cleanup[]

--
oc::
+
--
endif::[]
[#eventing-run-oc-trigger-broker-cleanup]
[source,bash,subs="attributes+,+macros",linenums]
----
oc -n {tutorial-namespace} delete -f eventing-aloha-sink.yaml
oc -n {tutorial-namespace} delete -f eventing-bonjour-sink.yaml
oc -n {tutorial-namespace} delete -f trigger-helloaloha.yaml
oc -n {tutorial-namespace} delete -f trigger-hellobonjour.yaml
oc -n {tutorial-namespace} delete -f curler.yaml
----
copyToClipboard::eventing-run-oc-trigger-broker-cleanup[]
ifndef::workshop[]
--
====
endif::[]
