[[source-to-sink]]
== Eventing Source to Sink
include::_attributes.adoc[]

//Define vars
:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus
:service-file: service.yaml

[#eventing-source]
== Event Source

*Knative Eventing Sources* are software components that emit events.  The job of a Source is to connect to, drain, capture and potentially buffer events; often from an external system and then relay those events to the *Sink*.

Knative Eventing Sources installs the following four sources out-of-the-box:

[source,bash,subs="+quotes,attributes+,+macros"]
----
$ *kubectl api-resources --api-group='sources.eventing.knative.dev'*
NAME              APIGROUP                      NAMESPACED   KIND
apiserversources  sources.eventing.knative.dev  true         ApiServerSource
containersources  sources.eventing.knative.dev  true         ContainerSource
cronjobsources    sources.eventing.knative.dev  true         CronJobSource
sinkbindings      sources.eventing.knative.dev  true         SinkBinding
----

.link:{github-repo}/{eventing-repo}/eventing-hello-sink.yaml[eventing-hello-sink.yaml]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: sources.eventing.knative.dev/v1
kind: CronJobSource #<1>
metadata:
  name: event-greeter-cronjob-source
spec: #<2>
  schedule: "*/2 * * * *"
  data: '{"message": "Thanks for doing Knative Tutorial"}'
  sink: 
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: eventinghello
----

<1> The type of event source, the eventing system deploys a bunch of sources out of the box and it also provides way to deploy custom resources
<2> spec will be unique per source, per kind


[#eventing-sink]
== Event Sink

*Knative Eventing Sink* is how you specify the event receiver -- that is the consumer of the event--. Sinks can be invoked directly in a point-to-point fashion by referencing them via the Event Source's `sink` as shown below:

.link:{github-repo}/{eventing-repo}/eventing-hello-sink.yaml[eventing-hello-sink.yaml]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: sources.eventing.knative.dev/v1
kind: CronJobSource
metadata:
  name: event-greeter-cronjob-source
spec:
  schedule: "*/2 * * * *"
  data: '{"message": "Thanks for doing Knative Tutorial"}'
  sink:  #<1>
    apiVersion: serving.knative.dev/v1 #<2>
    kind: Service
    name: eventinghello #<3>
----

<1> sink can target any Kubernetes Service or 
<2> a Knative Service
<3> Deployed as "eventinghello"

[NOTE]
====
Event Source can define the attributes that it wishes to receive via the 
spec.  In the above example it defines **schedule**(the cron expression) and **data** that will be sent as part of the event.

When you xref:{eventing-repo}/eventing.adoc#eventing-watch-logs[watch logs], you will notice this data being delivered to the service.
====

Run the following commands to create the event source resources:

[#eventing-create-event-source]
=== Create Event Source

:doc-sec: event-src-svc
:url: {github-repo}/{eventing-repo}/eventing-hello-sink.yaml
:url-alt-text: event-source-svc.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

[#eventing-verify-event-source]
==== Verification
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-verify-event-source]
[source,bash,subs="attributes+,+macros"]
----
kubectl -n {tutorial-namespace} get cronjobsources.sources.eventing.knative.dev 
----
copyToClipboard::eventing-run-verify-event-source[]
--
oc::
+
--
endif::[]
[#eventing-run-oc-verify-event-source]
[source,bash,subs="attributes+,+macros"]
----
oc -n {tutorial-namespace} get cronjobsources.sources.eventing.knative.dev 
----
copyToClipboard::eventing-run-oc-verify-event-source[]
ifndef::workshop[]
--
====
endif::[]

Running  the above command should return the following result:

[source,bash,subs="attributes+,+macros"]
----
NAME                       AGE
event-greeter-cronjob-source  39s
----

include::partial$eventing-snippets.adoc[tag=cronjob-source]

[#eventing-sink-service]
== Create Sink Service 

Run the following command to create the Knative service that will be used as the subscriber for the cron events:

.link:{github-repo}/{eventing-repo}/eventinghello-source.yaml[eventinghello-source.yaml]
[source,yaml,subs="attributes+,+macros"]
----
include::ROOT:example$eventing/eventinghello-source.yaml[]
----

[#eventing-deploy-sink-service]
=== Deploy Sink Service

Run the following commands to create the service:

:doc-sec: deploy-sink-service
:url: {github-repo}/{eventing-repo}/eventing/eventinghello-source.yaml
:url-alt-text: eventinghello-source.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

You can xref:{eventing-repo}/eventing.adoc#eventing-watch-logs[watch logs] to see the cron job source sending an event every 1 minute.

[#eventing-see-what-you-have-deployed]
=== See what you have deployed

==== sources
include::partial$knative-objects.adoc[tag=knative-event-cronjob-sources]

==== services
include::partial$knative-objects.adoc[tag=knative-event-services]

[#eventing-cleanup]
== Cleanup
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-src-svc-cleanup]
[source,bash,subs="attributes+,+macros",linenums]
----
kubectl -n {tutorial-namespace} delete -f eventinghello-source.yaml
kubectl -n {tutorial-namespace} delete -f eventing-hello-sink.yaml
----
copyToClipboard::eventing-run-src-svc-cleanup[]

--
oc::
+
--
endif::[]
[#eventing-run-oc-src-svc-cleanup]
[source,bash,subs="attributes+,+macros",linenums]
----
oc -n {tutorial-namespace} delete -f eventinghello-source.yaml
oc -n {tutorial-namespace} delete -f eventing-hello-sink.yaml
----
copyToClipboard::eventing-run-oc-src-svc-cleanup[]
ifndef::workshop[]
--
====

endif::[]

