= Setup
include::_attributes.adoc[]

ifndef::workshop[]
[[prerequisite]]
== Prerequisite CLI tools

The following CLI tools are required for running the exercises in this tutorial. Please have them installed and configured before you get started with any of the tutorial chapters.

[cols="3*^,3*.",options="header"]
|===
|**Tool**|**macOS**|**Fedora**

| `git`
| https://git-scm.com/download/mac
| `dnf install git`

| `Docker`
| https://docs.docker.com/docker-for-mac/install
| `dnf install docker`

| https://github.com/wercker/stern[stern]
| `brew install stern`
| `sudo curl --output /usr/local/bin/stern -L https://github.com/wercker/stern/releases/download/1.6.0/stern_linux_amd64 && sudo chmod +x /usr/local/bin/stern`

| https://github.com/mikefarah/yq[yq]
| `brew install yq`
|  https://github.com/mikefarah/yq/releases/latest

| https://httpie.org/[httpie]
| `brew install httpie`
| `dnf install httpie`

| https://github.com/JoeDog/siege[siege]
| `brew install siege`
| `dnf install siege`

| watch
| `brew install watch`
| `dnf install procps-ng`

| kubectx and kubens
| `brew install kubectx`
| https://github.com/ahmetb/kubectx

|===

[#remote-docker-repository]
== Remote Repository
For some parts of the tutorial, you will be pushing and pulling container images to and from a remote image repository. You will need an account with publish rights. 

[IMPORTANT]
====
Knative works best with any container registry that support `v2_2` schema e.g. https://gcr.io[Google Container Registry], https://hub.docker.com[Docker Hub].
====

[#download-tutorial-sources]
== Download Tutorial Sources
Before we start setting up the environment, let's clone the tutorial sources and set the `TUTORIAL_HOME` environment variable to point to the root directory of the tutorial:

ifdef::workshop-version[]
[#cloneRepo]
[source,bash,subs="attributes+,+macros"]
----
git clone -b {workshop-version} https://github.com/redhat-developer-demos/knative-tutorial 
----
copyToClipboard::cloneRepo[]
endif::[]

ifndef::workshop-version[]
[#cloneRepo]
[source,bash,subs="attributes+,+macros"]
----
git clone https://github.com/redhat-developer-demos/knative-tutorial 
----
copyToClipboard::cloneRepo[]
endif::[]

ifndef::workshop[]
[IMPORTANT,subs="attributes+,+macros"]
====

This tutorial was developed and tested with:

- Knative `{knative-version}`
- Minikube `{minikube-version}`
- OpenShift `{openshift-version}`
====
endif::[]

ifndef::workshop[]
[#kubernetes-cluster]
== Choose your Kubernetes Cluster

Knative can be installed only on Kubernetes cluster. The following section shows how to install Knative on vanilla https://kubernetes.io[Kubernetes] or on Red Hat https://www.openshift.com[Openshift] -- an enterprise grade Kubernetes platform --

[tabs]
====
Kubernetes::
+
--
include::partial$minikube-setup.adoc[]
--
OpenShift::
+
--
include::partial$openshift-setup.adoc[]
--
====
endif::[]
endif::[]

ifdef::workshop[]
include::workshop:partial$openshift-setup.adoc[]
endif::[]