= Basics and Fundamentals
include::_attributes.adoc[]

:service-file: service.yaml
:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus

At the end of this chapter you will be able to :

* Deploy a Knative service.
* Deploy multiple revisions of a service.
* Run different revisions of a service via traffic definition.

ifndef::workshop[]
[#basics-prerequisite]
== Prerequisite

include::partial$prereq-cli.adoc[]

endif::[]

[#basics-deploy-service]
== Deploy Service

Navigate to the tutorial chapter's `knative` folder:

[#basics-nav-folder]
[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/{basics-repo}/knative
----
copyToClipboard::basics-nav-folder[]

The following snippet shows what a Knative service YAML looks like:

.link:{github-repo}/{basics-repo}/knative/{service-file}[{service-file}]
[source,yaml,subs="+macros,attributes+"]
----
include::ROOT:example$02-basics/{service-file}[]
----

The service can be deployed using the following command:
 
:doc-sec: basics-rev1-deploy
:url: {github-repo}/{basics-repo}/knative/{service-file}
:url-alt-text: {service-file}
include::ROOT:partial$deploy-knative-resources.adoc[]

After successful deployment of the service we should see a Kubernetes Deployment named similar to `greeter-nsrbr-deployment` available:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#basics-run-get-deployments]
[source,bash,subs="+macros,+attributes"]
----
kubectl get deployments -n {tutorial-namespace}
----
copyToClipboard::basics-run-get-deployments[]
--
oc::
+
--
endif::[]
[#basics-run-oc-get-deployments]
[source,bash,linenums,subs="+macros,+attributes"]
----
oc get deployments -n {tutorial-namespace}
----
copyToClipboard::basics-run-oc-get-deployments[]
ifndef::workshop[]
--
====
endif::[]

[NOTE]
====
* The actual deployment name may vary in your setup
====

[#basics-invoke-service]
== Invoke Service
ifndef::workshop[]
[tabs]
====
Kubernetes::
+
--
:k8s-env: minikube
:k8s-cli: kubectl
:doc-sec: bis
include::ROOT:partial$invoke-service.adoc[tags=**;!workshop-call;!workshop-call-params]
--
OpenShift::
+
--
:k8s-env: openshift
:k8s-cli: oc
:doc-sec: bis
include::ROOT:partial$invoke-service.adoc[tag=workshop-call]
--
====
endif::[]

ifdef::workshop[]
:k8s-env: openshift
:k8s-cli: oc
:doc-sec: bis-01
include::ROOT:partial$invoke-service.adoc[tag=workshop-call]
endif::[]

The `http` command should return a response containing a line similar to **Hi  greeter => '6fee83923a9f' : 1**

NOTE: Sometimes the response might not be returned immediately especially when the pod is coming up from dormant state. In that case, repeat service invocation.

[#basics-see-what-you-have-deployed]
== See what you have deployed

The service-based deployment strategy that we did now will create many Knative resources, the following commands will help you to query and find what has been deployed.

[#basics-show-knative-services]
=== service 

include::partial$knative-objects.adoc[tag=knative-services]

[#basics-show-knative-configs]
=== configuration

include::partial$knative-objects.adoc[tag=knative-configs]

[#basics-show-knative-routes]
=== routes

include::partial$knative-objects.adoc[tag=knative-routes]

When the service was invoked with `http $IP_ADDRESS 'Host:greeter.knativetutorial.example.com'`, you noticed that we added a **Host** header to the request with value `greeter.knativetutorial.example.com`. This FQDN is automatically assigned to your Knative service by the Knative Routes and uses the following format: `**<service-name>.<namespace>.<domain-suffix>**`.

[NOTE]
====
* The domain suffix in this case __example.com__ is configurable via the config map **config-domain** of **knative-serving** namespace.
====

[#rev1-basics-show-knative-revisions]
=== revisions
:doc-sec: rev1
include::partial$knative-objects.adoc[tag=knative-revisions]

[TIP]
====
* add `-oyaml` to the commands above to see more details
====

[#deploying-new-revision]
== Deploy a New Revision of a Service

As Knative follows https://12factor.net[12-Factor] application principles, any https://12factor.net/config[configuration] change will trigger creation of a new revision of the deployment.
 
To deploy a new revision of the greeter service, we will add an environment variable to the existing service as shown below:

[#basics-service-rev2]
=== Service revision 2

:service-file: service-env.yaml

.link:{github-repo}/{basics-repo}/knative/{service-file}[{service-file}]
[source,yaml,subs="+macros,attributes+"]
----
include::ROOT:example$02-basics/{service-file}[]
----

Adding an environment variable that will be used as the message prefix

Let us deploy the new revision using the command:

:doc-sec: basics-rev2-deploy
:url: {github-repo}/{basics-repo}/knative/{service-file}
:url-alt-text: {service-file}
include::ROOT:partial$deploy-knative-resources.adoc[]


After successful deployment of the service we should see a Kubernetes deployment called `greeter-v2-deployment`.

Now if you list revisions, you will see two of them, named similar to `greeter-v1` and `greeter-v2`.

[#rev2-basics-show-knative-revisions]
=== revisions
:doc-sec: rev2
include::partial$knative-objects.adoc[tag=knative-revisions]

<<basics-invoke-service,Invoking Service>> will now show an output like **Namaste  greeter => '6fee83923a9f' : 1**, where __Namaste__ is the value we configured via environment variable in the Knative service resource file.

:service-file: service-pinned.yaml

[#basics-pinning-revision]
== Pinning Service to a Revision

As you noticed, Knative service always routes traffic to the **latest** revision of the service deployment. It is possible to split the traffic amongst the available revisions. 

As we already know the at got two revisions namely `greeter-v1` and `greeter-v2`. The `traffic` block in the Knative `service` specification helps in pinning a service to a particular revision or split traffic among multiple revisions.

[TIP]
====
You can use the <<rev1-basics-show-knative-revisions, show Knative service revisions>> command to find the available revisions for the greeter service.
====

=== Service pinned to first revision

.link:{github-repo}/{basics-repo}/knative/{service-file}[{service-file}]
[source,yaml,linenums,subs="attributes+,+macros"]
----
include::ROOT:example$02-basics/{service-file}[]
----

The above service definition creates three sub-routes(named after traffic **tags**) to existing `greeter` route.

- **current** - The revision is going to have all 100% traffic distribution
- **prev** - The previously active revision, which will now have zero traffic 
- **latest** - The route pointing to any latest service deployment, by setting to zero we are making sure the latest revision is not picked up automatically.

Let us redeploy the greeter service by pinning it to the `greeter-v1`:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#run-pinned-revision]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} apply -f {service-file}
----
copyToClipboard::run-pinned-revision[]
--
oc::
+
--
endif::[]
[#run-oc-pinned-revision]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace}  apply -f {service-file}
----
copyToClipboard::run-oc-pinned-revision[]
ifndef::workshop[]
--
====
endif::[]

Let us list the available sub-routes:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#run-traffic-sub-routes]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get ksvc greeter -oyaml \
 | yq r - 'status.traffic[*].url'
----
copyToClipboard::run-traffic-sub-routes[]
--
oc::
+
--
endif::[]
[#run-oc-traffic-sub-routes]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} get ksvc greeter -oyaml \
  | yq r - 'status.traffic[*].url'
----
copyToClipboard::run-oc-traffic-sub-routes[]
ifndef::workshop[]
--
====
endif::[]

The above command should return you three sub-routes for the main `greeter` route:

[source,bash,subs="+macros,attributes"]
----
- http://current-greeter.knativetutorial.example.com #<1>
- http://prev-greeter.knativetutorial.example.com #<2>
- http://latest-greeter.knativetutorial.example.com #<3>
----

<1> the sub route for the traffic tag `current`
<2> the sub route for the traffic tag `prev`
<3> the sub route for the traffic tag `latest`

<<basics-invoke-service,Invoking Service>> will produce output similar to **Hi  greeter => '6fee83923a9f' : 1**

As per the current traffic distribution, the `greeter` route will always return response from revision `greeter-v1` (traffic tag `current`)

[TIP]
====
ifndef::workshop[]
* If you are in vanilla Kubernetes cluster you can also try the using the above urls in the `Host` header of the http command to see them scaling the respective deployments to get the result.
endif::[]
* If you are on OpenShift then you can directly invoke the urls to see the response of those respective revision
====

[#basics-cleanup]
== Cleanup
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#basics-run-cleanup]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} delete services.serving.knative.dev greeter
----
copyToClipboard::basics-run-cleanup[]
--
oc::
+
--
endif::[]
[#basics-run-oc-cleanup]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} delete services.serving.knative.dev greeter
----
copyToClipboard::basics-run-oc-cleanup[]
ifndef::workshop[]
--
====
endif::[]
