= Basics and Fundamentals
include::_attributes.adoc[]

:service-file: service.yaml
:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus

At the end of this chapter you will be able to :

* Deploy a Knative service.
* Deploy multiple revisions of a service.
* Run different revisions of a service via traffic definition.

ifndef::workshop[]
[#basics-prerequisite]
== Prerequisite

include::partial$prereq-cli.adoc[]

endif::[]

[#basics-deploy-service]
== Deploy Service

Navigate to the tutorial chapter's folder {basics-repo}:

[#basics-nav-folder]
[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/{basics-repo}
----
copyToClipboard::basics-nav-folder[]

The following snippet shows what a Knative service YAML looks like:

.link:{github-repo}/{basics-repo}/{service-file}[{service-file}]
[source,yaml,subs="+macros,attributes+"]
----
include::ROOT:example${basics-repo}/{service-file}[]
----

The service can be deployed using the following command:
 
:doc-sec: basics-rev1-deploy
:url: {github-repo}/{basics-repo}/knative/{service-file}
:url-alt-text: {service-file}
include::ROOT:partial$deploy-knative-resources.adoc[]

After successful deployment of the service we should see a Kubernetes Deployment named similar to `greeter-nsrbr-deployment` available:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#basics-run-get-deployments]
[source,bash,subs="+macros,+attributes"]
----
kubectl get deployments -n {tutorial-namespace}
----
copyToClipboard::basics-run-get-deployments[]
--
oc::
+
--
endif::[]
[#basics-run-oc-get-deployments]
[source,bash,linenums,subs="+macros,+attributes"]
----
oc get deployments -n {tutorial-namespace}
----
copyToClipboard::basics-run-oc-get-deployments[]
ifndef::workshop[]
--
====
endif::[]

[NOTE]
====
* The actual deployment name may vary in your setup
====

[#basics-invoke-service]
== Invoke Service
ifndef::workshop[]
[tabs]
====
Kubernetes::
+
--
:k8s-env: minikube
:k8s-cli: kubectl
:doc-sec: bis
include::ROOT:partial$invoke-service.adoc[tags=**;!workshop-call;!workshop-call-params]
--
OpenShift::
+
--
:k8s-env: openshift
:k8s-cli: oc
:doc-sec: bis
include::ROOT:partial$invoke-service.adoc[tag=workshop-call]
--
====
endif::[]

ifdef::workshop[]
:k8s-env: openshift
:k8s-cli: oc
:doc-sec: bis-01
include::ROOT:partial$invoke-service.adoc[tag=workshop-call]
endif::[]

The `http` command should return a response containing a line similar to **Hi  greeter => '6fee83923a9f' : 1**

NOTE: Sometimes the response might not be returned immediately especially when the pod is coming up from dormant state. In that case, repeat service invocation.

[#basics-see-what-you-have-deployed]
== See what you have deployed

The service-based deployment strategy that we did now will create many Knative resources, the following commands will help you to query and find what has been deployed.

[#basics-show-knative-services]
=== service 

include::partial$knative-objects.adoc[tag=knative-services]

[#basics-show-knative-configs]
=== configuration

include::partial$knative-objects.adoc[tag=knative-configs]

[#basics-show-knative-routes]
=== routes

include::partial$knative-objects.adoc[tag=knative-routes]

When the service was invoked with `http $IP_ADDRESS 'Host:greeter.knativetutorial.example.com'`, you noticed that we added a **Host** header to the request with value `greeter.knativetutorial.example.com`. This FQDN is automatically assigned to your Knative service by the Knative Routes and uses the following format: `**<service-name>.<namespace>.<domain-suffix>**`.

[NOTE]
====
* The domain suffix in this case __example.com__ is configurable via the config map **config-domain** of **knative-serving** namespace.
====

[#rev1-basics-show-knative-revisions]
=== revisions
:doc-sec: rev1
include::partial$knative-objects.adoc[tag=knative-revisions]

[TIP]
====
* add `-oyaml` to the commands above to see more details
====

[#deploying-new-revision]
== Deploy a New Revision of a Service

.Twelve-factor app
****
https://12factor.net/[12factor.net] defines the twelve-factor app as a methodology for building software-as-a-service apps that:

- Use declarative formats for setup automation, to minimize time and cost for new developers joining the project;
- Have a clean contract with the underlying operating system, offering maximum portability between execution environments;
- Are suitable for deployment on modern cloud platforms, obviating the need for servers and systems administration;
- Minimize divergence between development and production, enabling continuous deployment for maximum agility;
- And can scale up without significant changes to tooling, architecture, or development practices.
- The twelve-factor methodology can be applied to apps written in any programming language, and which use any combination of backing services (database, queue, memory cache, etc).
****
 
To deploy a new revision of the greeter service, we will add an environment variable to the existing service as shown below:

[#basics-service-rev2]
=== Service revision 2

:service-file: service-env.yaml

.link:{github-repo}/{basics-repo}/{service-file}[{service-file}]
[source,yaml,subs="+macros,attributes+"]
----
include::ROOT:example$basics/{service-file}[]
----

Adding an environment variable that will be used as the message prefix

Let us deploy the new revision using the command:

:doc-sec: basics-rev2-deploy
:url: {github-repo}/{basics-repo}/knative/{service-file}
:url-alt-text: {service-file}
include::ROOT:partial$deploy-knative-resources.adoc[]


After successful deployment of the service we should see a Kubernetes deployment called `greeter-v2-deployment`.

Now if you list revisions, you will see two of them, named similar to `greeter-v1` and `greeter-v2`.

[#rev2-basics-show-knative-revisions]
=== revisions
:doc-sec: rev2
include::partial$knative-objects.adoc[tag=knative-revisions]

<<basics-invoke-service,Invoking Service>> will now show an output like **Namaste  greeter => '6fee83923a9f' : 1**, where __Namaste__ is the value we configured via environment variable in the Knative service resource file.

[#basics-cleanup]
== Cleanup
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#basics-run-cleanup]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} delete services.serving.knative.dev greeter
----
copyToClipboard::basics-run-cleanup[]
--
oc::
+
--
endif::[]
[#basics-run-oc-cleanup]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} delete services.serving.knative.dev greeter
----
copyToClipboard::basics-run-oc-cleanup[]
ifndef::workshop[]
--
====
endif::[]
