[doc-sec='']

#tag::knative-services[]
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#knative-services]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace}  get services.serving.knative.dev greeter 
----
copyToClipboard::knative-services[]
--
oc::
+
--
endif::[]
[#oc-knative-services]
[source,bash,subs="+macros,+attributes"]
----
oc --namespace {tutorial-namespace}  get services.serving.knative.dev greeter 
----
copyToClipboard::oc-knative-services[]
ifndef::workshop[]
--
====
endif::[]

#end::knative-services[]

#tag::knative-configs[]
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#knative-configs]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace} get configurations.serving.knative.dev greeter
----
copyToClipboard::knative-configs[]
--
oc::
+
--
endif::[]
[#oc-knative-configs]
[source,bash,subs="+macros,+attributes"]
----
oc --namespace {tutorial-namespace} get configurations.serving.knative.dev greeter
----
copyToClipboard::oc-knative-configs[]
ifndef::workshop[]
--
====
endif::[]

#end::knative-configs[]

#tag::knative-routes[]
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#knative-routes]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace} get routes.serving.knative.dev greeter
----
copyToClipboard::knative-routes[]
--
oc::
+
--
endif::[]
[#oc-knative-routes]
[source,bash,subs="+macros,+attributes"]
----
oc --namespace {tutorial-namespace} get routes.serving.knative.dev greeter
----
copyToClipboard::oc-knative-routes[]
ifndef::workshop[]
--
====
endif::[]

#end::knative-routes[]

#tag::knative-revisions[]
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#{doc-sec}knative-revisions]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace} get rev \
--selector=serving.knative.dev/service=greeter \
--sort-by="{.metadata.creationTimestamp}"
----
copyToClipboard::{doc-sec}knative-revisions[]
--
oc::
+
--
endif::[]
[#{doc-sec}-oc-knative-revisions]
[source,bash,subs="+macros,+attributes"]
----
oc --namespace {tutorial-namespace} get rev \
 --selector=serving.knative.dev/service=greeter \
 --sort-by="{.metadata.creationTimestamp}"
----
copyToClipboard::{doc-sec}-oc-knative-revisions[]
ifndef::workshop[]
--
====
endif::[]

#end::knative-revisions[]

#tag::knative-config-revisions[]

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#knative-config-revisions]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace} get rev \
  -l serving.knative.dev/configuration=greeter \
  --sort-by="{.metadata.creationTimestamp}"
----
copyToClipboard::knative-config-revisions[]

--
oc::
+
--
endif::[]
[#oc-knative-config-revisions]
[source,bash,subs="+macros,+attributes"]
----
oc --namespace {tutorial-namespace} get rev \
  -l serving.knative.dev/configuration=greeter \
  --sort-by="{.metadata.creationTimestamp}"
----
copyToClipboard::oc-knative-config-revisions[]
ifndef::workshop[]
--
====
endif::[]

#end::knative-config-revisions[]

#tag::knative-build[]
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#knative-build]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace} get builds.build.knative.dev event-greeter-build
----
copyToClipboard::knative-build[]
--
oc::
+
--
endif::[]
[#oc-knative-build]
[source,bash,subs="+macros,+attributes"]
----
oc --namespace {tutorial-namespace} get builds.build.knative.dev event-greeter-build
----
copyToClipboard::oc-knative-build[]
ifndef::workshp[]
--
====
endif::[]

#end::knative-build[]

#tag::knative-build-templates[]
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#knative-build-templates]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace} get buildtemplates.build.knative.dev build-java-maven
----
copyToClipboard::knative-build-templates[]
--
oc::
+
--
endif::[]
[#oc-knative-build-templates]
[source,bash,subs="+macros,+attributes"]
----
oc --namespace {tutorial-namespace} get buildtemplates.build.knative.dev build-java-maven
----
copyToClipboard::oc-knative-build-templates[]
ifndef::workshop[]
--
====
endif::[]
#end::knative-build-templates[]

#tag::knative-event-channel[]
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#knative-event-channel]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace} get channels.eventing.knative.dev ch-event-greeter
----
copyToClipboard::knative-event-channel[]
--
oc::
+
--
endif::[]
[#oc-knative-event-channel]
[source,bash,subs="+macros,+attributes"]
----
oc --namespace {tutorial-namespace} get channels.eventing.knative.dev ch-event-greeter
----
copyToClipboard::oc-knative-event-channel[]

ifndef::workshop[]
--
====
endif::[]
#end::knative-event-channel[]

#tag::knative-event-cronjob-sources[]
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#knative-event-sources]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace} get cronjobsources.sources.eventing.knative.dev  event-greeter-cronjob-source
----
copyToClipboard::knative-event-sources[]
--
oc::
+
--
endif::[]
[#oc-knative-event-sources]
[source,bash,subs="+macros,+attributes"]
----
oc --namespace {tutorial-namespace} get cronjobsources.sources.eventing.knative.dev event-greeter-cronjob-source
----
copyToClipboard::oc-knative-event-sources[]
ifndef::workshop[]
--
====
endif::[]
#end::knative-event-cronjob-sources[]

#tag::knative-event-subscribers[]
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#knative-event-subscribers]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace} get subscriptions.eventing.knative.dev event-greeter-subscriber
----
copyToClipboard::knative-event-subscribers[]
--
oc::
+
--
endif::[]
[#oc-knative-event-subscribers]
[source,bash,subs="+macros,+attributes"]
----
oc --namespace {tutorial-namespace} get subscriptions.eventing.knative.dev event-greeter-subscriber
----
copyToClipboard::oc-knative-event-subscribers[]
ifndef::workshop[]
--
====
endif::[]

#end::knative-event-subscribers[]

#tag::knative-event-services[]
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#knative-services]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace}  get services.serving.knative.dev event-greeter  
----
copyToClipboard::knative-services[]
--
oc::
+
--
endif::[]
[#oc-knative-services]
[source,bash,subs="+macros,+attributes"]
----
# get a Knative Service (short name ksvc) called greeter
oc --namespace {tutorial-namespace}  get services.serving.knative.dev event-greeter 
----
copyToClipboard::oc-knative-services[]
ifndef::workshop[]
--
====
endif::[]

#end::knative-event-services[]

#tag::knative-triggers[]
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#knative-triggers]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace}  get triggers.eventing.knative.dev event-greeter-trigger  
----
copyToClipboard::knative-triggers[]
--
oc::
+
--
endif::[]
[#oc-knative-triggers]
[source,bash,subs="+macros,+attributes"]
----
oc --namespace {tutorial-namespace}  get triggers.eventing.knative.dev event-greeter-trigger 
----
copyToClipboard::oc-knative-triggers[]
ifndef::workshop[]
--
====
endif::[]

#end::knative-triggers[]

#tag::knative-container-event-sources[]
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#knative-container-event-sources]
[source,bash,subs="+macros,+attributes"]
----
kubectl --namespace {tutorial-namespace} get containersources.sources.eventing.knative.dev heartbeat-event-source
----
copyToClipboard::knative-container-event-sources[]
--
oc::
+
--
endif::[]
[#oc-knative-container-event-sources]
[source,bash,subs="+macros,+attributes"]
----
oc --namespace {tutorial-namespace} get containersources.sources.eventing.knative.dev heartbeat-event-source
----
copyToClipboard::oc-knative-container-event-sources[]
ifndef::workshop[]
--
====
endif::[]
#end::knative-container-event-sources[]
