[#start-minikube]
.**Configure and Start Minikube**

Before installing Knative and its components, we need to create a Minikube virtual machine and deploy Kubernetes into it.

Download https://kubernetes.io/docs/setup/minikube[minikube] and add it to your path.

[[setup-minikube-start]]
[source,bash,subs="+macros,+attributes"]
----
minikube profile knative #<1>

minikube start -p knative --memory=8192 --cpus=6 \#<2> 
  --kubernetes-version=v1.12.0 \#<3> 
  --vm-driver=hyperkit \#<4>  
  --disk-size=50g \
  --extra-config=apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
----
copyToClipboard::setup-minikube-start[]

<1> Setting Minikube profile to **knative** so that all future Minikube commands are executed with this profile context
<2> Starting a profile named **knative**
<3> Minimum Kubernetes version needs to be 1.12, refer to issue https://github.com/knative/serving/issues/3067 for more details.
<4> On macOS. On Linux, please use `--vm-driver=kvm2`

**Install Istio**

[#run-install-istio]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply --filename https://raw.githubusercontent.com/knative/serving/{knative-serving-version}/third_party/istio-1.1.7/istio-crds.yaml && \
kubectl apply --filename https://raw.githubusercontent.com/knative/serving/{knative-serving-version}/third_party/istio-1.1.7/istio-lean.yaml
----
copyToClipboard::run-install-istio[]

[NOTE,subs="+macros,+attributes"]
=====
* As Knative need only Istio Ingress Gateway and Pilot, we will use Knative Istio lean install, which just installs the required component
* Installation of Istio components will take some time and it is highly recommended that you start Knative components installation only after you have verified that all Istio component pods are running. The Istio pods can be watched using the command:

[#setup-watch-istio-pods]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n istio-system get pods -w 
----
copyToClipboard::setup-watch-istio-pods[]

You can use kbd:[CTRL + c ] to terminate the watch
=====

A successful Istio install will have the pods running in the `istio-system` namespace as shown below:

[source,bash]
----
NAME                                     READY   STATUS      RESTARTS   AGE
cluster-local-gateway-579cfd9fdd-9hb7p   0/1     Running     0          62s
istio-ingressgateway-776c54f7c4-m9qz2    1/2     Running     0          62s
istio-init-crd-10-mc7h5                  0/1     Completed   0          68s
istio-init-crd-11-86lsf                  0/1     Completed   0          68s
istio-pilot-75b876b994-w8x7t             0/1     Running     0          62s
istio-pilot-75b876b994-w8x7t             1/1     Running     0          67s
istio-ingressgateway-776c54f7c4-m9qz2    2/2     Running     0          69s
----

**Install Custom Resource Definitions**

[#run-knative-crd-install]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply --selector knative.dev/crd-install=true \
  --filename {knative-serving-repo}/{knative-serving-version}/serving.yaml \
  --filename {knative-eventing-repo}/{knative-eventing-version}/release.yaml
----
copyToClipboard::run-knative-crd-install[]

[NOTE]
=====
First time when you run the above command will show some warnings and error as shown below, you can either safely ignore them or re-running the above command will cause the errors to disappear.

[source,bash]
----
unable to recognize "https://github.com/knative/serving/releases/download/v0.7.1/serving.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/eventing/releases/download/v0.7.1/release.yaml": no matches for kind "ClusterChannelProvisioner" in version "eventing.knative.dev/v1alpha1"
----
=====

**Install Knative Serving**

[#run-install-knative-serving]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply --selector networking.knative.dev/certificate-provider!=cert-manager \
  --filename {knative-serving-repo}/{knative-serving-version}/serving.yaml
----
copyToClipboard::run-install-knative-serving[]

[NOTE]
=====
As the Knative serving components are getting installed, you can watch their status using the following command:

[#setup-watch-knative-serving-pods]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n knative-serving get pods -w 
----
copyToClipboard::setup-watch-knative-serving-pods[]

You can use kbd:[CTRL + c ] to terminate the watch
=====

A successful Knative serving installation will have its pods running in the `knative-serving` namespace as shown below:

[source,bash]
----
NAME                                READY   STATUS    RESTARTS   AGE
activator-bc968b649-r6l82           1/1     Running   0          36s
autoscaler-66f5cd8774-kjs9k         1/1     Running   0          36s
controller-68977d579c-phltz         1/1     Running   0          36s
networking-istio-5d8d9d574d-5lfsl   1/1     Running   0          36s
webhook-894c8cb4d-7hl97             1/1     Running   0          36s
----

**Install Knative Eventing** 

[#run-install-knative-eventing]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply --selector networking.knative.dev/certificate-provider!=cert-manager \
  --filename {knative-eventing-repo}/{knative-eventing-version}/release.yaml
----
copyToClipboard::run-install-knative-eventing[]

[NOTE,subs="+macros,+attributes"]
=====
As the Knative eventing components are getting installed, you can watch their status using the following commands:

[#setup-watch-knative-eventing-pods]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n knative-eventing get pods -w 
----
copyToClipboard::setup-watch-knative-eventing-pods[]

You can use kbd:[CTRL + c ] to terminate the watch
=====

A successful Knative eventing installation will have the following pods running in the `knative-eventing` namespace:

.knative-eventing namespace

[source,bash]
----
NAME                                           READY   STATUS    RESTARTS   AGE
eventing-controller-5c5f664ddb-9bmq9           1/1     Running   0          3m40s
eventing-webhook-7ccb674dc6-qjtwp              1/1     Running   0          3m40s
imc-controller-9bcf67784-j7m2h                 1/1     Running   0          3m40s
imc-dispatcher-7c6c7d798c-kvzf7                1/1     Running   0          3m40s
in-memory-channel-controller-8dfd9c8df-cpsph   1/1     Running   0          3m40s
in-memory-channel-dispatcher-8776cb68f-wntmb   1/1     Running   0          3m39s
sources-controller-6f4d494fb9-8wkj4            1/1     Running   0          3m40s
----

**Configuring Kubernetes namespace**

We will use a non default Kubernetes namespace called `{tutorial-namespace}` for all the tutorial exercises.

[#setup-knative-tutorial-ns]
[source,bash,subs="+macros,+attributes"]
----
kubectl create namespace {tutorial-namespace}
----
copyToClipboard::setup-knative-tutorial-ns[]

[TIP]
=====
The kubens utility installed as part of https://github.com/ahmetb/kubectx[kubectx] allows for easy switching between Kubernetes namespaces.

[#setup-knative-tutorial-kubens]
[source,bash,subs="+macros,+attributes"]
----
kubens {tutorial-namespace}
----
copyToClipboard::setup-knative-tutorial-kubens[]

=====
