[#start-minikube]
**Configure and Start Minikube**

Before installing Knative and its components, we need to create a Minikube virtual machine and deploy Kubernetes into it.

Download https://kubernetes.io/docs/setup/minikube[minikube] and add it to your path.

[#setup-minikube-start]
[source,bash,subs="+macros,+attributes"]
----
minikube profile {tutorial-namespace} #<1>

minikube start -p {tutorial-namespace} --memory=8192 --cpus=6 \#<1> 
  --kubernetes-version=v1.14.0 \
  --vm-driver=hyperkit \#<2>  
  --disk-size=50g \
  --extra-config='apiserver.enable-admission-plugins=LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook' \
  --insecure-registry='10.0.0.0/24' #<3>
----
copyToClipboard::setup-minikube-start[]

<1> Setting Minikube profile to **knative** so that all future Minikube commands are executed with this profile context
<2> On macOS/windows. On Linux, please use `--vm-driver=kvm2`
<3> Make the internal registry to be insecure registry

[#minikube-enable-registry]
**Enable Internal Registry**

[#minikube-enable-registry-run]
[source,bash,subs="+macros,attributes+"]
----
minikube addons enable registry
----
copyToClipboard::minikube-enable-registry-run[]

NOTE: It will take few mins for the registry to be enabled, you can watch the status using `kubectl get pods -n kube-system -w  | grep registry`

A successful enable of <<minikube-enable-registry,registry>> will show the following pods when running the command:

[#minikube-check-registry]
[source,bash,subs="attributes+,+macros"]
----
kubectl get pods -n kube-system | grep registry
----
copyToClipboard::minikube-check-registry[]

[source,bash]
----
registry-7c5hg                             1/1     Running   0          29m
registry-proxy-cj6dj                       1/1     Running   0          29m
----

**Navigate to registry helper folder:**

[#minikube-registry-helper-nav]
[source,bash,subs="attributes+,+macros"]
----
cd $TUTORIAL_HOME/apps/minikube-registry-helper
----
copyToClipboard::minikube-registry-helper-nav[]

**Deploy Registry Helper**

As part of some exercises in the tutorial, we need to push and pull images to local internal registry. To make push and pull smoother we will have a helper deployed so that we can use some common names like `dev.local`, `example.com` as registry aliases for internal registry

**Add entries to minikube host file**

[#minikube-add-entry-to-host]
[source,bash,subs="attributes+,+macros"]
----
kubectl apply -n kube-system -f registry-aliases-config.yaml &&\
kubectl apply -n kube-system -f node-etc-hosts-update.yaml
----
copyToClipboard::minikube-add-entry-to-host[]

[IMPORTANT]
=====
Wait for the Daemonset to be running before proceeding to next step, the status of the Daemonset can be viewed via `kubectl get pods -n kube-system -w`, you can do kbd:[CTRL+c] to end the watch.
=====

Check if the entries are added to minikube node host file

[#minikube-check-host-entry]
[source,bash,subs="attributes+,+macros"]
----
minikube ssh -- sudo cat /etc/hosts
----
copyToClipboard::minikube-check-host-entry[]

A successful daemonset run will show the minikube node `/etc/hosts` file with the following entries:

[source,bash]
----
127.0.0.1       localhost
127.0.1.1 demo
10.111.151.121  dev.local
10.111.151.121  example.com
----

[NOTE]
======
The IP for `dev.local` and `example.com` will match the **CLUSTER-IP** of the internal registry. To know the Cluster IP run the command:

[#minikube-check-registry-ip]
[source,bash,subs="attributes+,+macros"]
----
kubectl get svc registry -n kube-system
----
copyToClipboard::minikube-check-registry-ip[]
======

[source,bash,subs="attributes+,+macros"]
----
NAME       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
registry   ClusterIP   10.111.151.121   <none>        80/TCP                  178m
----

**Update CoreDNS**

[#minikube-update-coredns]
[source,bash,subs="attributes+,+macros"]
----
./patch-coredns.sh
----
copyToClipboard::minikube-update-coredns[]

To check successful patch  run the following command 

[#check-coredns-cm]
[source,bash,subs="attributes+,+macros"]
----
kubectl get cm -n kube-system coredns -o yaml
----
copyToClipboard::check-coredns-cm[]

A successful patch will have the coredns updated ConfigMap `coredns` in `kube-system`

[source,yaml]
----
apiVersion: v1
data:
  Corefile: |-
    .:53 {
        errors
        health
        rewrite name dev.local registry.kube-system.svc.cluster.local
        rewrite name example.com registry.kube-system.svc.cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
----

**Install Istio**

[#run-install-istio]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply --filename https://raw.githubusercontent.com/knative/serving/{knative-serving-version}/third_party/istio-1.1.7/istio-crds.yaml && \
kubectl apply --filename https://raw.githubusercontent.com/knative/serving/{knative-serving-version}/third_party/istio-1.1.7/istio-lean.yaml
----
copyToClipboard::run-install-istio[]

[NOTE,subs="+macros,+attributes"]
=====
* As Knative need only Istio Ingress Gateway and Pilot, we will use Knative Istio lean install, which just installs the required component
* Installation of Istio components will take some time and it is highly recommended that you start Knative components installation only after you have verified that all Istio component pods are running. The Istio pods can be watched using the command:

[#setup-watch-istio-pods]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n istio-system get pods -w 
----
copyToClipboard::setup-watch-istio-pods[]

You can use kbd:[CTRL + c ] to terminate the watch
=====

A successful Istio install will have the pods running in the `istio-system` namespace as shown below:

[source,bash]
----
NAME                                     READY   STATUS      RESTARTS   AGE
cluster-local-gateway-579cfd9fdd-9hb7p   0/1     Running     0          62s
istio-ingressgateway-776c54f7c4-m9qz2    1/2     Running     0          62s
istio-init-crd-10-mc7h5                  0/1     Completed   0          68s
istio-init-crd-11-86lsf                  0/1     Completed   0          68s
istio-pilot-75b876b994-w8x7t             0/1     Running     0          62s
istio-pilot-75b876b994-w8x7t             1/1     Running     0          67s
istio-ingressgateway-776c54f7c4-m9qz2    2/2     Running     0          69s
----

**Install Custom Resource Definitions**

[#run-knative-crd-install]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply --selector knative.dev/crd-install=true \
  --filename {knative-serving-repo}/{knative-serving-version}/serving.yaml \
  --filename {knative-eventing-repo}/{knative-eventing-version}/release.yaml
----
copyToClipboard::run-knative-crd-install[]

[NOTE]
=====
First time when you run the above command will show some warnings and error as shown below, you can either safely ignore them or re-running the above command will cause the errors to disappear.

[source,bash]
----
unable to recognize "https://github.com/knative/serving/releases/download/v0.7.1/serving.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/eventing/releases/download/v0.7.1/release.yaml": no matches for kind "ClusterChannelProvisioner" in version "eventing.knative.dev/v1alpha1"
----
=====

**Install Knative Serving**

[#run-install-knative-serving]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply --selector networking.knative.dev/certificate-provider!=cert-manager \
  --filename {knative-serving-repo}/{knative-serving-version}/serving.yaml
----
copyToClipboard::run-install-knative-serving[]

[NOTE]
=====
As the Knative serving components are getting installed, you can watch their status using the following command:

[#setup-watch-knative-serving-pods]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n knative-serving get pods -w 
----
copyToClipboard::setup-watch-knative-serving-pods[]

You can use kbd:[CTRL + c ] to terminate the watch
=====

A successful Knative serving installation will have its pods running in the `knative-serving` namespace as shown below:

[source,bash]
----
NAME                                READY   STATUS    RESTARTS   AGE
activator-bc968b649-r6l82           1/1     Running   0          36s
autoscaler-66f5cd8774-kjs9k         1/1     Running   0          36s
controller-68977d579c-phltz         1/1     Running   0          36s
networking-istio-5d8d9d574d-5lfsl   1/1     Running   0          36s
webhook-894c8cb4d-7hl97             1/1     Running   0          36s
----

**Install Knative Eventing** 

[#run-install-knative-eventing]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply --selector networking.knative.dev/certificate-provider!=cert-manager \
  --filename {knative-eventing-repo}/{knative-eventing-version}/release.yaml
----
copyToClipboard::run-install-knative-eventing[]

[NOTE,subs="+macros,+attributes"]
=====
As the Knative eventing components are getting installed, you can watch their status using the following commands:

[#setup-watch-knative-eventing-pods]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n knative-eventing get pods -w 
----
copyToClipboard::setup-watch-knative-eventing-pods[]

You can use kbd:[CTRL + c ] to terminate the watch
=====

A successful Knative eventing installation will have the following pods running in the `knative-eventing` namespace:

.knative-eventing namespace

[source,bash]
----
NAME                                           READY   STATUS    RESTARTS   AGE
eventing-controller-5c5f664ddb-9bmq9           1/1     Running   0          3m40s
eventing-webhook-7ccb674dc6-qjtwp              1/1     Running   0          3m40s
imc-controller-9bcf67784-j7m2h                 1/1     Running   0          3m40s
imc-dispatcher-7c6c7d798c-kvzf7                1/1     Running   0          3m40s
in-memory-channel-controller-8dfd9c8df-cpsph   1/1     Running   0          3m40s
in-memory-channel-dispatcher-8776cb68f-wntmb   1/1     Running   0          3m39s
sources-controller-6f4d494fb9-8wkj4            1/1     Running   0          3m40s
----

**Configuring Kubernetes namespace**

We will use a non default Kubernetes namespace called `{tutorial-namespace}` for all the tutorial exercises.

[#setup-knative-tutorial-ns]
[source,bash,subs="+macros,+attributes"]
----
kubectl create namespace {tutorial-namespace}
----
copyToClipboard::setup-knative-tutorial-ns[]

[TIP]
=====
The https://github.com/ahmetb/kubens[kubens] utility installed as part of https://github.com/ahmetb/kubectx[kubectx] allows for easy switching between Kubernetes namespaces.

[#setup-knative-tutorial-kubens]
[source,bash,subs="+macros,+attributes"]
----
kubens {tutorial-namespace}
----
copyToClipboard::setup-knative-tutorial-kubens[]

=====
