[#install-knative-openshift]

**OpenShift**

Knative Serving and Eventing install needs OpenShift v4.x, you need to have one provisioned using https://try.openshift.com[try.openshift.com]or can use any existing OpenShift4 cluster.

Once you have your cluster, you can download the latest OpenShift client(oc) from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/[here] and add to your path.

We will be using https://coreos.com/operators/[Kubernetes Operators] to install Knative serving and eventing components on OpenShift. OpenShift is integrated with https://operatorhub.io/[OperatorHub] that allows you to install the components(using Kubernetes operators) from within OpenShift web console.

[IMPORTANT]
=====
* The Knative Eventing components are right now available as community components and is currently not supported by Red Hat.
=====

**Login as admin**

Login to OpenShift console using the cluster admin credentials.

**Install catalog sources**

[#install-csc]
[source,bash,subs="+macros,+attributes"]
----
oc apply -f "pass:[$TUTORIAL_HOME]/install/redhat-operators-csc.yaml" \
  -f "pass:[$TUTORIAL_HOME]/install/community-operators-csc.yaml" 
----
copyToClipboard::install-csc[]

It will take few minutes for the operators to be installed and reconciled, you can watch the status using the command:

[#check-operators-status]
[source,bash,subs="+macros,+attributes"]
----
watch 'oc get csv -n openshift-operators'
----
copyToClipboard::check-operators-status[]

[NOTE]
=====
You can terminate the watch using the command kbd:[Ctrl+c]
=====

**Install Knative Serving**

[#install-knative-serving]
[source,bash,subs="+macros,+attributes"]
----
oc apply -f "pass:[$TUTORIAL_HOME]/install/knative-serving/subscription.yaml"
----
copyToClipboard::install-knative-serving[]

It will take few minutes for the Knative serving components to be installed, you can watch the status using:

[#check-knative-serving]
[source,bash,subs="+macros,+attributes"]
----
oc get pods -n knative-serving -w 
----
copyToClipboard::check-knative-serving[]

NOTE: You can terminate the watch using the command kbd:[Ctrl+c]

**Install Knative Eventing**

[#install-knative-eventing]
[source,bash,subs="+macros,+attributes"]
----
oc apply -f "pass:[$TUTORIAL_HOME]/install/knative-eventing/subscription.yaml"
----
copyToClipboard::install-knative-eventing[]

It will take few minutes for the Knative eventing components to be installed, you can watch the status using:

[#check-knative-eventing]
[source,bash,subs="+macros,+attributes"]
----
oc get pods -n knative-eventing -w 
----
copyToClipboard::check-knative-eventing[]

NOTE: You can terminate the watch using the command kbd:[Ctrl+c]
