[#install-knative-openshift]

**OpenShift**

Knative Serving and Eventing install needs OpenShift4, you need to have one provisioned using https://try.openshift.com[try.openshift.com] or can use any existing OpenShift4 cluster.

Once you have your cluster, you can download the latest OpenShift client(oc) from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/[here] and add to your path.

[#oc-version-check]
[source,bash,subs="+macros,+attributes"]
----
oc version 
----
copyToClipboard::oc-version-check[]

The output should show oc version >=4.1

[source,bash]
----
oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0+b4261e0", GitCommit:"b4261e07ed", GitTreeState:"clean", BuildDate:"2019-07-06T03:16:01Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+73b5d76", GitCommit:"73b5d76", GitTreeState:"clean", BuildDate:"2019-09-23T16:18:51Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
----

We will be using https://coreos.com/operators/[Kubernetes Operators] to install Serverless (Knative Serving) and Knative Eventing components on OpenShift. 

[IMPORTANT]
=====
* The Knative Serving community component is deprecated on OpenShift and we will be using Red Hat serverless operator.
* The Knative Eventing components are right now available as `knative-eventing` community operator and is currently not supported by Red Hat.
=====

**Login as admin**

Login to OpenShift console using the cluster admin credentials.

**Create projects**

[NOTE]
======
OpenShift is integrated with https://operatorhub.io/[OperatorHub] that allows you to install the components(using Kubernetes operators) from within OpenShift web console. But for the installation we will be using the command line mode via `oc`
======

[#create-projects]
[source,bash,subs="+macros,+attributes"]
----
oc adm new-project istio-system && \
oc adm new-project knative-serving && \
oc adm new-project knative-eventing && \
oc adm new-project knativetutorial  
----
copyToClipboard::create-projects[]

**Install catalog sources**

[#install-csc]
[source,bash,subs="+macros,+attributes"]
----
oc apply -f "pass:[$TUTORIAL_HOME]/install/redhat-operators-csc.yaml" \
  -f "pass:[$TUTORIAL_HOME]/install/community-operators-csc.yaml" 
----
copyToClipboard::install-csc[]

It will take few minutes for the operators to be installed and reconciled, check the status using the command:

[#check-csc]
[source,bash,subs="+macros,+attributes"]
----
oc -n openshift-marketplace get csc  
----
copyToClipboard::check-csc[]

A successful reconciliation should show an output like:

[source,bash,subs="+macros,+attributes"]
-----
NAME                           STATUS      MESSAGE                                       AGE
community-operators-packages   Succeeded   The object has been successfully reconciled   62s
redhat-operators-packages      Succeeded   The object has been successfully reconciled   62s
-----

Open a new terminal and start a watch on the command `oc get csv -n openshift-operators`. For further reference in the setup we will call this terminal as **WATCH_WINDOW**.

[#check-operators-status]
[source,bash,subs="+macros,+attributes"]
----
watch 'oc get csv -n openshift-operators -ocustom-columns-file=$TUTORIAL_HOME/install/csv-columns.txt'
----
copyToClipboard::check-operators-status[]

[NOTE]
=====
You can terminate the watch using the command kbd:[Ctrl+c]
=====

**Install Servicemesh**

Subscribe to Servicemesh via https://operstorhub.io[OperatorHub]

[#subscribe-to-servicemesh]
[source,bash,subs="+macros,+attributes"]
----
oc apply -f "pass:[$TUTORIAL_HOME]/install/servicemesh/subscription.yaml"
----
copyToClipboard::subscribe-to-servicemesh[]

NOTE: It will take few minutes for the servicemesh and its dependent components to be installed. Watch the status in the WATCH_WINDOW

A successful servicemesh subscription install should show the output in WATCH_WINDOW like:

[source,bash]
-----
NAME                                         VERSION               PHASE
elasticsearch-operator.4.1.20-201910102034   4.1.20-201910102034   Succeeded
jaeger-operator.v1.13.1                      1.13.1                Succeeded
kiali-operator.v1.0.6                        1.0.6                 Succeeded
servicemeshoperator.v1.0.1                   1.0.1                 Succeeded
-----

The servicemesh operator needs to be copied to the `istio-system` project before we can create a `ServiceMeshControlPlane` and `ServiceMeshMemberRoll` custom resources, you can watch the status using the command:

[#watch-istio-system-operator-copy]
[source,bash,subs="+macros,+attributes"]
----
watch 'oc get csv -n istio-system -ocustom-columns-file=$TUTORIAL_HOME/install/csv-columns.txt'
----
copyToClipboard::watch-istio-system-operator-copy[]

NOTE: It will take few seconds for the operator to be copied

Once you see the following status, you can terminate the watch using kbd:[Ctrl+c]:

[source,bash,subs="+macros,+attributes"]
----
NAME                                         VERSION               PHASE
elasticsearch-operator.4.1.20-201910102034   4.1.20-201910102034   Succeeded
jaeger-operator.v1.13.1                      1.13.1                Succeeded
kiali-operator.v1.0.6                        1.0.6                 Succeeded
servicemeshoperator.v1.0.1                   1.0.1                 Succeeded
----

[#create-scmp]
[source,bash,subs="+macros,+attributes"]
----
oc create -f "pass:[$TUTORIAL_HOME]/install/servicemesh/smcp.yaml" && \
oc create -f "pass:[$TUTORIAL_HOME]/install/servicemesh/smmr.yaml"
----
copyToClipboard::create-scmp[]

It will take few minutes for the servicemesh components to be installed, you can watch the status using the command:

[#watch-istio-system-status]
[source,bash,subs="+macros,+attributes"]
----
oc get pods -n istio-system -w 
----
copyToClipboard::watch-istio-system-status[]

A successful servicemesh install should show the following pods:

[source,bash,subs="+macros,+attributes"]
----
NAME                                     READY   STATUS    RESTARTS   AGE
cluster-local-gateway-7795cc7956-mqmq7   1/1     Running   0          92s
istio-citadel-f88bdd688-c52z8            1/1     Running   0          2m58s
istio-galley-f8f96c6bf-x7f4k             1/1     Running   0          2m48s
istio-ingressgateway-65bf84457c-7rh5t    1/1     Running   0          92s
istio-pilot-7f57f8bb5b-cr2qr             1/1     Running   0          110s
----

IMPORTANT: These are the minimal set of servicemesh components required for serverless.

**Install Serverless**

Subscribe to Serverless via https://operstorhub.io[OperatorHub]

[#subscribe-to-knative-serving]
[source,bash,subs="+macros,+attributes"]
----
oc apply -f "pass:[$TUTORIAL_HOME]/install/knative-serving/subscription.yaml"
----
copyToClipboard::subscribe-to-knative-serving[]

[IMPORTANT]
======
Wait for the subscription **PHASE** to be **Installed** before proceeding to next step. You can watch the status in the WATCH_WINDOW.
======

A successful knative serving subscription install should show the output in WATCH_WINDOW like:

[source,bash]
-----
NAME                                         VERSION               PHASE
elasticsearch-operator.4.1.20-201910102034   4.1.20-201910102034   Succeeded
jaeger-operator.v1.13.1                      1.13.1                Succeeded
kiali-operator.v1.0.6                        1.0.6                 Succeeded
serverless-operator.v1.0.0                   1.0.0                 Succeeded
servicemeshoperator.v1.0.1                   1.0.1                 Succeeded
-----

The serverless operator needs to be copied to the `knative-serving` project before we can create a `KnativeServing` custom resource, you can watch the status using the command:

[#watch-knative-serving-operator-copy]
[source,bash,subs="+macros,+attributes"]
----
watch 'oc get csv -n knative-serving -ocustom-columns-file=$TUTORIAL_HOME/install/csv-columns.txt'
----
copyToClipboard::watch-knative-serving-operator-copy[]

NOTE: It will take few seconds for the operator to be copied

Once you see the following status, you can terminate the watch using kbd:[Ctrl+c]:

[source,bash,subs="+macros,+attributes"]
----
NAME                                         VERSION               PHASE
elasticsearch-operator.4.1.20-201910102034   4.1.20-201910102034   Succeeded
jaeger-operator.v1.13.1                      1.13.1                Succeeded
kiali-operator.v1.0.6                        1.0.6                 Succeeded
serverless-operator.v1.0.0                   1.0.0                 Succeeded
servicemeshoperator.v1.0.1                   1.0.1                 Succeeded
----

[#install-knative-serving]
[source,bash,subs="+macros,+attributes"]
----
oc apply -f "pass:[$TUTORIAL_HOME]/install/knative-serving/cr.yaml"
----
copyToClipboard::install-knative-serving[]

It will take few minutes for the Knative serving components to be installed, you can watch the status using:

[#check-knative-serving]
[source,bash,subs="+macros,+attributes"]
----
oc get pods -n knative-serving -w 
----
copyToClipboard::check-knative-serving[]

NOTE: You can terminate the watch using the command kbd:[Ctrl+c]

A successful serverless install will show the following pods in `knative-serving` namespace:

[source,bash]
----
NAME                                    READY   STATUS    RESTARTS   AGE
activator-78464cc84-vq9wp               1/1     Running   1          103s
autoscaler-57479674d6-hlvx7             1/1     Running   0          102s
controller-6fcb5b4b78-flq8d             1/1     Running   0          97s
networking-certmanager-8c6d68d4-cmf7x   1/1     Running   0          97s
networking-istio-644984496f-db58w       1/1     Running   0          96s
webhook-84b96fdc6f-vbpxm                1/1     Running   1          96s
----

**Install Knative Eventing**

[#install-knative-eventing]
[source,bash,subs="+macros,+attributes"]
----
oc apply -f "pass:[$TUTORIAL_HOME]/install/knative-eventing/subscription.yaml"
----
copyToClipboard::install-knative-eventing[]

[IMPORTANT]
======
Wait for the subscription **PHASE** to be **Installed** before proceeding to next step. You can watch the status in the WATCH_WINDOW.
======

A successful knative eventing subscription install should show the output in WATCH_WINDOW like:

[source,bash]
-----
NAME                                         VERSION               PHASE
elasticsearch-operator.4.1.20-201910102034   4.1.20-201910102034   Succeeded
jaeger-operator.v1.13.1                      1.13.1                Succeeded
kiali-operator.v1.0.6                        1.0.6                 Succeeded
knative-eventing-operator.v0.8.0             0.8.0                 Succeeded
serverless-operator.v1.0.0                   1.0.0                 Succeeded
servicemeshoperator.v1.0.1                   1.0.1                 Succeeded
-----

The knative-eventing operator needs to be copied to the `knative-eventing` project before we can create a `KnativeEventing` custom resource, you can watch the status using the command:

[#watch-knative-eventing-operator-copy]
[source,bash,subs="+macros,+attributes"]
----
watch 'oc get csv -n knative-eventing -ocustom-columns-file=$TUTORIAL_HOME/install/csv-columns.txt'
----
copyToClipboard::watch-knative-eventing-operator-copy[]

NOTE: It will take few seconds for the operator to be copied

Once you see the following status, you can terminate the watch using kbd:[Ctrl+c]:

[source,bash,subs="+macros,+attributes"]
----
NAME                                         VERSION               PHASE
elasticsearch-operator.4.1.20-201910102034   4.1.20-201910102034   Succeeded
jaeger-operator.v1.13.1                      1.13.1                Succeeded
kiali-operator.v1.0.6                        1.0.6                 Succeeded
knative-eventing-operator.v0.8.0             0.8.0                 Succeeded
serverless-operator.v1.0.0                   1.0.0                 Succeeded
servicemeshoperator.v1.0.1                   1.0.1                 Succeeded
----

It will take few minutes for the Knative eventing components to be installed, you can watch the status using:

[#check-knative-eventing]
[source,bash,subs="+macros,+attributes"]
----
oc get pods -n knative-eventing -w 
----
copyToClipboard::check-knative-eventing[]

NOTE: You can terminate the watch using the command kbd:[Ctrl+c]

A successful Knative Eventing install will show the following pods in Knative eventing namespace:

[source,bash]
-----
NAME                                            READY   STATUS    RESTARTS   AGE
eventing-controller-758d785bf7-jr7bh            1/1     Running   0          2m4s
eventing-webhook-7ff46cd45f-w8d9v               1/1     Running   0          2m3s
imc-controller-75d7f598df-4knn4                 1/1     Running   0          113s
imc-dispatcher-77f565585c-z6d8x                 1/1     Running   0          113s
in-memory-channel-controller-6b4967d97b-x2hcj   1/1     Running   0          2m
in-memory-channel-dispatcher-8bbcd4f9-kxmcw     1/1     Running   0          118s
sources-controller-788874d5fc-8jqrz             1/1     Running   0          2m4s
-----

Congratulations! You have now installed all the required components to run the tutorial exercises. You can terminate the WATCH_WINDOW using kbd:[Ctrl+c].

**Navigate to tutorial project**

[#nav-to-tutorial-project]
[source,bash,subs="+macros,+attributes"]
----
oc project knativetutorial
----
copyToClipboard::nav-to-tutorial-project[]
