= Eventing Source to Service
include::_attributes.adoc[]

//Define vars
:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus
:service-file: service.yaml

[#eventing-source]
== Event Source

The event source listens to external events e.g. a kafka topic or for a file on a FTP server. It is responsible to drain the received event(s) along with its data to a configured https://en.wikipedia.org/wiki/Sink_(computing)[sink].

include::partial$eventing-snippets.adoc[tag=eventing-nav-folder]

[#eventing-create-event-source]
=== Create Event Source
.link:{github-repo}/{eventing-repo}/knative/event-source-svc.yaml[event-source-svc.yaml]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource #<1>
metadata:
  name: event-greeter-cronjob-source
spec:
  schedule: "* * * * *"
  data: '{"message": "Thanks for doing Knative Tutorial"}'
  sink: #<2>
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-greeter
----

<1> The type of event source, the eventing system deploys a bunch of sources out of the box and it also provides way to deploy custom resources
<2> The service(sink) where the event data will be sent

[NOTE]
====
Event Source can define the attributes that it wishes to receive via the 
spec.  In the above example it defines **schedule**(the cron expression) and **data** that will be sent as part of the event.

When you xref:{eventing-repo}/eventing.adoc#eventing-watch-logs[watch logs], you will notice this data being delivered to the service.
====

Run the following commands to create the event source resources:

:doc-sec: event-src-svc
:url: {github-repo}/{eventing-repo}/knative/event-source-svc.yaml
:url-alt-text: event-source-svc.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

[#eventing-verify-event-source]
==== Verification
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-verify-event-source]
[source,bash,subs="attributes+,+macros"]
----
kubectl -n {tutorial-namespace} get cronjobsources.sources.eventing.knative.dev 
----
copyToClipboard::eventing-run-verify-event-source[]
--
oc::
+
--
endif::[]
[#eventing-run-oc-verify-event-source]
[source,bash,subs="attributes+,+macros"]
----
oc -n {tutorial-namespace} get cronjobsources.sources.eventing.knative.dev 
----
copyToClipboard::eventing-run-oc-verify-event-source[]
ifndef::workshop[]
--
====
endif::[]

Running  the above command should return the following result:

[source,bash,subs="attributes+,+macros"]
----
NAME                       AGE
event-greeter-cronjob-source  39s
----

include::partial$eventing-snippets.adoc[tag=cronjob-source]

[#eventing-sink-service]
== Create Sink Service 

[#eventing-gen-sink-service]
=== Generate Sink Service

Run the following command to create the Knative service that will be used as the subscriber for the cron events:

.link:{github-repo}/{eventing-repo}/knative/service.yaml[service.yaml]
[source,yaml,subs="attributes+,+macros"]
----
include::ROOT:example$05-eventing/service.yaml[]
----

[#eventing-deploy-sink-service]
=== Deploy Sink Service

Run the following commands to create the service:

:doc-sec: deploy-sink-service
:url: {github-repo}/{eventing-repo}/knative/service.yaml
:url-alt-text: service.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

You can xref:{eventing-repo}/eventing.adoc#eventing-watch-logs[watch logs] to see the cron job source sending an event every 1 minute.

[#eventing-see-what-you-have-deployed]
=== See what you have deployed

==== sources
include::partial$knative-objects.adoc[tag=knative-event-cronjob-sources]

==== services
include::partial$knative-objects.adoc[tag=knative-event-services]

[#eventing-cleanup]
== Cleanup
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-src-svc-cleanup]
[source,bash,subs="attributes+,+macros",linenums]
----
kubectl -n {tutorial-namespace} delete services.serving.knative.dev event-greeter
kubectl -n {tutorial-namespace} delete \
 cronjobsources.sources.eventing.knative.dev  event-greeter-cronjob-source
----
copyToClipboard::eventing-run-src-svc-cleanup[]

--
oc::
+
--
endif::[]
[#eventing-run-oc-src-svc-cleanup]
[source,bash,subs="attributes+,+macros",linenums]
----
oc -n {tutorial-namespace} delete services.serving.knative.dev event-greeter
oc -n {tutorial-namespace} delete \
 cronjobsources.sources.eventing.knative.dev  event-greeter-cronjob-source
----
copyToClipboard::eventing-run-oc-src-svc-cleanup[]
ifndef::workshop[]
--
====

NOTE: You can also delete xref:knative-tutorial-build:ROOT:build.adoc#build-apply-prereq-resources[pre-req resources] that were created if you don't need them anymore.

endif::[]

