= Eventing - Source to Subscriber
include::_attributes.adoc[]

//Define vars
:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus

[#eventing-channel]
== Channel(Sink)

The https://en.wikipedia.org/wiki/Event-driven_architecture#Event_channel[channel or sink] is an interface between the <<eventing-source,event source>> and the <<eventing-subscriber,subscriber>>.The channels are built in to store the incoming events and distribute the event data to the subscribers. When forwarding event to subscribers the channel transforms the event data as per http://cloudevents.io[CloudEvent] specification.

[#eventing-create-event-channel]
=== Create Event Channel
.link:{github-repo}/{eventing-repo}/knative/channel.yaml[channel.yaml]
[source,yaml,linenums]
----
include::ROOT:example$05-eventing/channel.yaml[]
----

- The name of the channel. Knative makes it addressable, i.e. resolveable to a target (a consumer service)
- The channel provisioner which is responsible for provisioning this channel. Various messaging implementations provide their own channel(s) via __ClusterChannelProvisioner__.

include::partial$eventing-snippets.adoc[tag=eventing-nav-folder]

Run the following commands to create the channel:

:doc-sec: eventing-run-source-sub
:url: {github-repo}/{eventing-repo}/knative/channel.yaml
:url-alt-text: channel.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

[#eventing-verify-event-channel]
==== Verification
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-verify-event-channel]
[source,bash,subs="attributes+,+macros"]
----
kubectl -n {tutorial-namespace} get channels.eventing.knative.dev 
----
copyToClipboard::eventing-run-verify-event-channel[]
--
oc::
+
--
endif::[]

[#eventing-run-oc-verify-event-channel]
[source,bash,subs="attributes+,+macros"]
----
oc -n {tutorial-namespace} get channels.eventing.knative.dev 
----
copyToClipboard::eventing-run-oc-verify-event-channel[]
ifndef::workshop[]
--
====
endif::[]

Running  the above command should return the following result:

[source,bash,subs="attributes+,+macros"]
----
NAME                       AGE
ch-event-greeter   39s
----

[#eventing-source]
== Event Source

The event source listens to external events e.g. a kafka topic or for a file on a FTP server. It is responsible to drain the received event(s) along with its data to a configured https://en.wikipedia.org/wiki/Sink_(computing)[sink].

[#eventing-create-event-source]
=== Create Event Source
.link:{github-repo}/{eventing-repo}/knative/event-source.yaml[event-source.yaml]
[source,yaml,subs="attributes+,+macros"]
----
include::ROOT:example$05-eventing/event-source.yaml[]
----

- The type of event source, the eventing system deploys a bunch of sources out of the box and it also provides way to deploy custom resources
- The channel(sink) where the event data will be drained

[NOTE,subs="macros+"]
====
Event Source can define the attributes that it wishes to receive via the 
spec.  In the above example it defines **schedule**(the the cron expression) and **data** that will be sent as part of the event.

When you xref:{eventing-repo}/eventing.adoc#eventing-watch-logs[watch logs], you will notice this data being delivered to the service.
====

Run the following commands to create the event source resources:

:doc-sec: eventing-run-apply-event-src
:url: {github-repo}/{eventing-repo}/knative/event-source.yaml
:url-alt-text: event-source.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

[#eventing-verify-event-source]
==== Verification
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-verify-event-src]
[source,bash,subs="attributes+,+macros"]
----
kubectl -n {tutorial-namespace} get cronjobsources.sources.eventing.knative.dev 
----
copyToClipboard::eventing-run-verify-event-src[]
--
oc::
+
--
endif::[]
[#eventing-run-oc-verify-event-src]
[source,bash,subs="attributes+,+macros"]
----
oc -n {tutorial-namespace} get cronjobsources.sources.eventing.knative.dev 
----
copyToClipboard::eventing-run-oc-verify-event-src[]
ifndef::workshop[]
--
====
endif::[]

Running  the above command should return the following result:

[source,bash,subs="attributes+,+macros"]
----
NAME                       AGE
event-greeter-cronjob-source  39s
----

include::partial$eventing-snippets.adoc[tag=cronjob-source]

[#eventing-subscriber]
== Event Subscriber

The event subscription is responsible of connecting the channel(sink) with the service. Once a service connected to a channel it starts receiving the events (cloud events).

[#eventing-create-subscriber]
=== Create Channel Subscriber
.link:{github-repo}/{eventing-repo}/knative/channel-subscriber.yaml[channel-subscriber.yaml]
[source,yaml,subs="attributes+,+macros"]
----
include::ROOT:example$05-eventing/channel-subscriber.yaml[]
----

Run the following commands to create the channel subscriber:

:doc-sec: create-subscriber
:url: {github-repo}/{eventing-repo}/knative/channel-subscriber.yaml
:url-alt-text: channel-subscriber.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

[#eventing-verify-subscriber]
==== Verification
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-verify-subscriber]
[source,bash,subs="attributes+,+macros"]
----
kubectl -n {tutorial-namespace} get subscriptions.eventing.knative.dev 
----
copyToClipboard::eventing-run-verify-subscriber[]
--
oc::
+
--
endif::[]
[#eventing-run-oc-verify-subscriber]
[source,bash,subs="attributes+,+macros"]
----
oc -n {tutorial-namespace} get subscriptions.eventing.knative.dev 
----
copyToClipboard::eventing-run-oc-verify-subscriber[]
ifndef::workshop[]
--
====
endif::[]

Running  the above command should return the following result:

[source,bash,subs="attributes+,+macros"]
----
NAME                       AGE
event-greeter-subscriber  39s
----

[#eventing-see-what-you-have-deployed]
=== See what you have deployed

==== channel
include::partial$knative-objects.adoc[tag=knative-event-channel]

==== sources
include::partial$knative-objects.adoc[tag=knative-event-cronjob-sources]

==== subscription
include::partial$knative-objects.adoc[tag=knative-event-subscribers]

TIP: Add `-oyaml` to the above commands to get more details about each object that were queried for. 

[#eventing-subscriber-service]
== Create subscriber Service 

[#eventing-gen-subscriber-service]
=== Generate Subscriber Service

Run the following command to create the knative service that will be used as the subscriber for the cron events:

.link:{github-repo}/{eventing-repo}/knative/service.yaml[service.yaml]
[source,yaml,subs="attributes+,+macros"]
----
include::ROOT:example$05-eventing/service.yaml[]
----

[#eventing-deploy-subscriber-service]
=== Deploy Subscriber Service

Run the following commands to create the service:

:doc-sec: deploy-sub-svc
:url: {github-repo}/{eventing-repo}/knative/service.yaml
:url-alt-text: service.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

You can xref:{eventing-repo}/eventing.adoc#eventing-watch-logs[watch logs] to see the cron job source sending an event every 1 minute.

[#eventing-cleanup]
== Cleanup
ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#eventing-run-cleanup2]
[source,bash,subs="attributes+,+macros",linenums]
----
kubectl -n {tutorial-namespace} delete services.serving.knative.dev event-greeter
kubectl -n {tutorial-namespace} delete \
 cronjobsources.sources.eventing.knative.dev  event-greeter-cronjob-source
kubectl -n {tutorial-namespace} delete channels.eventing.knative.dev ch-event-greeter
kubectl -n {tutorial-namespace} delete subscriptions.eventing.knative.dev event-greeter-subscriber
----
copyToClipboard::eventing-run-cleanup2[]

--
oc::
+
--
endif::[]
[#eventing-run-oc-cleanup2]
[source,bash,subs="attributes+,+macros",linenums]
----
oc -n {tutorial-namespace} delete services.serving.knative.dev event-greeter
oc -n {tutorial-namespace} delete \
 cronjobsources.sources.eventing.knative.dev  event-greeter-cronjob-source
oc -n {tutorial-namespace} delete channels.eventing.knative.dev ch-event-greeter
oc -n {tutorial-namespace} delete subscriptions.eventing.knative.dev event-greeter-subscriber
----
copyToClipboard::eventing-run-oc-cleanup2[]
ifndef::workshop[]
--
====

NOTE: You can also delete xref:knative-tutorial-build:ROOT:build.adoc#build-apply-prereq-resources[pre-req resources] that were created if you don't need them anymore.

endif::[]
